# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""BigQuery tool used by the Google Trends executor agent."""

import json
import logging
import os

from google.api_core.exceptions import Forbidden
from google.cloud import bigquery

logger = logging.getLogger(__name__)

# The SQL executed here is generated by an LLM, so it must be bounded. A query
# that omits the refresh_date range predicate scans the whole table, and a
# prompt-injected one could be worse. BigQuery rejects a job up front when it
# would exceed maximum_bytes_billed, which makes this a real ceiling rather
# than a best-effort one.
#
# The value is chosen from measurement, not taste: the widest legitimate query
# in the few-shot set scans 3.91 GB, while dropping the range predicate scans
# 10.19 GB. 8 GiB sits between the two — it blocks the full scan and leaves
# roughly 2x headroom for normal use. Raise it if you widen the lookback.
_MAX_BYTES_BILLED = 8 * 1024**3  # 8 GiB
_QUERY_TIMEOUT_SECONDS = 60.0

_GENERIC_ERROR = (
    "Error executing BigQuery query. The query may be invalid or may "
    "exceed the configured scan limit; see the service logs for "
    "details."
)
# One-click deploys run as a platform identity (e.g. the Agent Runtime
# service agent) that has no BigQuery permissions until someone grants them.
# Say so plainly: the person who clicked Deploy rarely reads service logs.
_PERMISSION_HINT = (
    "BigQuery refused the query: this agent's runtime identity is not "
    "allowed to run BigQuery jobs. Grant it roles/bigquery.user on the "
    "project (see the Permissions section of the recipe README)."
)


def clean_sql_query(text: str) -> str:
    """Strips markdown fences and stray escapes from a generated SQL string."""
    return (
        text.replace("\\n", " ")
        .replace("\n", " ")
        .replace("\\", "")
        .replace("```sql", "")
        .replace("```", "")
        .strip()
    )


def execute_bigquery_sql(sql: str) -> str:
    """Executes a BigQuery SQL query and returns the result as a JSON string."""
    cleaned_sql = clean_sql_query(sql)
    logger.debug("Executing BigQuery SQL query: %s", cleaned_sql)
    try:
        # The client uses the GOOGLE_CLOUD_PROJECT environment variable.
        client = bigquery.Client(project=os.getenv("GOOGLE_CLOUD_PROJECT"))
        job_config = bigquery.QueryJobConfig(
            maximum_bytes_billed=_MAX_BYTES_BILLED
        )
        query_job = client.query(cleaned_sql, job_config=job_config)
        # timeout bounds how long we wait; maximum_bytes_billed bounds cost.
        results = query_job.result(timeout=_QUERY_TIMEOUT_SECONDS)

        # Convert RowIterator to a list of dictionaries
        sql_results = [dict(row) for row in results]

        # Return the results as a JSON string.
        if not sql_results:
            return "Query returned no results."
        # Use json.dumps for proper JSON formatting, handle non-serializable
        # types like datetime
        return (
            json.dumps(sql_results, default=str)
            .replace("```sql", "")
            .replace("```", "")
        )
    except Forbidden as e:
        # 403 also covers non-IAM refusals (e.g. quota); only an IAM denial
        # gets the permission hint.
        if any(err.get("reason") == "accessDenied" for err in e.errors or []):
            logger.exception("BigQuery permission denied")
            return _PERMISSION_HINT
        logger.exception("BigQuery query failed")
        return _GENERIC_ERROR
    except Exception:
        # Log the detail for the operator; return a generic message so raw
        # backend errors (which can name projects, datasets and tables) are
        # not handed back to the model or the end user.
        logger.exception("BigQuery query failed")
        return _GENERIC_ERROR
